---
# handlers file for ftp_install_role
    - name: Restart vsftpd
      service: 
        name: vsftpd 
        state: restarted
    - name: Apply new SELinux context
      command: restorecon -irv "{{ anon_folder }}"